apiVersion: v1
kind: Service
metadata:
  name: parcel-api
  namespace: app
  labels:
    app: parcel-api
    team: greenlogistics
    env: production
spec:
  selector:
    app: parcel-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
