# Deny-all par défaut dans le namespace app
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: app
  labels:
    team: greenlogistics
    env: production
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
# parcel-api : accepte trafic ingress + peut parler à postgres
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-parcel-api
  namespace: app
spec:
  podSelector:
    matchLabels:
      app: parcel-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: tracker-front
        - podSelector:
            matchLabels:
              app: notifier
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: postgres
      ports:
        - port: 5432
    - to:
        - namespaceSelector: {}  # DNS
      ports:
        - port: 53
          protocol: UDP
---
# gps-ingestor : accepte trafic ingress + peut parler à Redpanda
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gps-ingestor
  namespace: app
spec:
  podSelector:
    matchLabels:
      app: gps-ingestor
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: messaging
      ports:
        - port: 9092
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
---
# notifier : peut parler à Redpanda, parcel-api, et MailHog
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-notifier
  namespace: app
spec:
  podSelector:
    matchLabels:
      app: notifier
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: messaging
      ports:
        - port: 9092
    - to:
        - podSelector:
            matchLabels:
              app: parcel-api
      ports:
        - port: 3000
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: mail
      ports:
        - port: 1025
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
