apiVersion: v1
kind: Service
metadata:
  name: gps-ingestor
  namespace: app
  labels:
    app: gps-ingestor
    team: greenlogistics
    env: production
spec:
  selector:
    app: gps-ingestor
  ports:
    - name: http
      port: 3001
      targetPort: 3001
