apiVersion: v1
kind: Service
metadata:
  name: tracker-front
  namespace: app
  labels:
    app: tracker-front
    team: greenlogistics
    env: production
spec:
  selector:
    app: tracker-front
  ports:
    - name: http
      port: 3002
      targetPort: 3002
